// Régions de Côte d'Ivoire
export const REGIONS_CI = [
  "Abidjan",
  "Bas-Sassandra", 
  "Comoé",
  "Denguélé",
  "Gôh-Djiboua",
  "Lacs",
  "Lagunes",
  "Montagnes",
  "Sassandra-Marahoué",
  "Savanes",
  "Vallée du Bandama",
  "Woroba",
  "Yamoussoukro",
  "Zanzan",
  "Haut-Sassandra",
  "Poro",
  "Gbêkê",
  "Indénié-Djuablin",
  "Tonkpi",
  "Cavally",
  "Bafing",
  "Bagoué",
  "Bélier",
  "Béré",
  "Bounkani",
  "Folon",
  "Gbôklé",
  "Gontougo",
  "Guémon",
  "Hambol",
  "Iffou",
  "Kabadougou",
  "La Mé",
  "Lôh-Djiboua",
  "Marahoué",
  "Moronou",
  "N'Zi",
  "Nawa",
  "San-Pédro",
  "Sud-Comoé",
  "Tchologo",
  "Worodougou"
];

export const DOCUMENT_TYPES = [
  'Facture',
  'Reçu',
  'Bon de commande',
  'Bon de livraison',
  'Contrat',
  'Autre justificatif',
];
